name: SectorServer
version: ${project.version}
main: koral.sectorserver.SectorServer
api-version: 1.16
commands:
  tp:
    usage: /tp [<player> (player) | (player) <x> <y> <z>]
  spawn:
  tpa:
    description: tpa request
    permission: sectorserver.tpa
    usage: /tpa <nick>
  tpaccept:
    description: tpa request
    permission: sectorserver.tpa
  tpdeny:
    description: tpa request
    permission: sectorserver.tpa
  msg:
    usage: /msg <nick> <wiadomosc>
    description: msg
    permission: sectorserver.msg
  msgtoggle:
    description: msg toggle
    permission: sectorserver.msg
  remote:
    permission: sectorserver.remote
  sockettest: