name: SectorServer
version: ${project.version}
main: koral.sectorserver.SectorServer
api-version: 1.16
commands:
  tp:
    usage: /tp [<player> (player) | (player) <x> <y> <z>]
  spawn:
  tpa:
    description: tpa request
    permission: guildsaddons.tpa
    usage: /tpa <nick>
  tpaccept:
    description: tpa request
    permission: guildsaddons.tpa
  tpdeny:
    description: tpa request
    permission: guildsaddons.tpa